"""
Django settings for projectNam project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-06uzer#^+v&t&!m@_#whyzqa!suqzco$5#jg%@_$t2&b@kdh++'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

import os  # noqa: E402

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,django,web').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'citas',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estáticos directamente desde gunicorn
    # (necesario porque en producción runserver no está activo).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AgendarCitasMedicas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AgendarCitasMedicas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Notificaciones: en desarrollo los correos se imprimen en la consola en vez
# de enviarse de verdad. NOTIFICAR_POR_EMAIL controla qué Notificador
# instancia NotificadorFactory.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
NOTIFICAR_POR_EMAIL = True

# --- Strangler Pattern: microservicio de Notificaciones (Flask) ---
# Cuando USAR_MICROSERVICIO_NOTIFICACIONES=True, el monolito delega el envío
# de notificaciones al microservicio Flask vía HTTP en lugar de enviarlas él
# mismo. La URL apunta al nombre del servicio en docker-compose.
USAR_MICROSERVICIO_NOTIFICACIONES = os.getenv(
    'USAR_MICROSERVICIO_NOTIFICACIONES', 'True'
).lower() in ('1', 'true', 'yes')
NOTIFICACIONES_SERVICE_URL = os.getenv(
    'NOTIFICACIONES_SERVICE_URL', 'http://notificaciones:5000'
)
NOTIFICACIONES_SERVICE_TIMEOUT = int(os.getenv('NOTIFICACIONES_SERVICE_TIMEOUT', '5'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Carpeta donde collectstatic reúne los estáticos para producción.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise sirve los estáticos comprimidos y con cache busting.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
