# Generated by Django 6.0.7 on 2026-08-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
                ('registro_medico', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
