# Generated by Django 4.2.30 on 2026-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='requiere_referido',
            field=models.BooleanField(default=False),
        ),
    ]
