# Generated by Django 4.2.30 on 2026-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_duracion_minutos_cita_requiere_referido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='paciente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
