# Generated by Django 4.2.30 on 2026-08-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_seed_especialidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidad_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='citas.especialidad'),
        ),
    ]
