# Generated by Django 6.0.8 on 2026-08-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_contract_especialidad_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
